on:
  push:
    tags:
    - 'v*'

name: Upload Release Asset

jobs:
  artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [{ 'os': 'darwin', 'target': 'amd64'}, { 'os': 'linux', 'target': 'amd64'}, { 'os': 'linux', 'target': '386'}]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.3'

    - name: Install dependencies
      run: go version

    - name: Create Artifact
      run: |
        GOOS=${{ matrix.target.os }} GOARCH=${{ matrix.target.arch }} go build -o syncher
        zip -j -r syncher_${{ matrix.target.os }}_${{ matrix.target.arch }}.zip syncher

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: syncher_${{ matrix.target.os }}_${{ matrix.target.arch }}
        path: syncher_${{ matrix.target.os }}_${{ matrix.target.arch }}.zip

  release:
    runs-on: ubuntu-latest
    needs: artifacts

    steps:
    - uses: actions/checkout@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Download syncher_darwin_amd64
      uses: actions/download-artifact@v2
      with:
        name: syncher_darwin_amd64

    - name: Release syncher_darwin_amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./syncher_darwin_amd64.zip
        asset_name: syncher_darwin_amd64.zip
        asset_content_type: application/zip

    - name: Download syncher_linux_amd64
      uses: actions/download-artifact@v2
      with:
        name: syncher_linux_amd64

    - name: Release syncher_linux_amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./syncher_linux_amd64.zip
        asset_name: syncher_linux_amd64.zip
        asset_content_type: application/zip

    - name: Download syncher_linux_386
      uses: actions/download-artifact@v2
      with:
        name: syncher_linux_386

    - name: Release syncher_linux_386
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./syncher_linux_386.zip
        asset_name: syncher_linux_386.zip
        asset_content_type: application/zip
