on:
  push:
    tags:
    - 'v*'

name: Upload Release Asset

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.3'

    - name: Install dependencies
      run: go version

    - name: Build OSX
      run: GOOS=darwin GOARCH=amd64 go build -o syncher

    - name: Create OSX asset
      run: zip -j -r syncher_darwin_amd64.zip syncher

    - name: Build Linux
      run: GOOS=linux GOARCH=amd64 go build -o syncher

    - name: Create OSX asset
      run: zip -j -r syncher_linux_amd64.zip syncher

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload OSX Asset
      id: upload-OSX-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ./syncher_darwin_amd64.zip
        asset_name: syncher_darwin_amd64.zip
        asset_content_type: application/zip

    - name: Upload Linux Asset
      id: upload-Linux-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ./syncher_linux_amd64.zip
        asset_name: syncher_linux_amd64.zip
        asset_content_type: application/zip
